//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowStuff {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowStuff.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   current theme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add an appointment to {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AgreeUseLocation {
            get {
                return ResourceManager.GetString("AgreeUseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   album과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add lockscreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuAddLockscreen {
            get {
                return ResourceManager.GetString("AppbarMenuAddLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add multiple과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuAddMultipleImage {
            get {
                return ResourceManager.GetString("AppbarMenuAddMultipleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuAddSingleImage {
            get {
                return ResourceManager.GetString("AppbarMenuAddSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuFitLockscreen {
            get {
                return ResourceManager.GetString("AppbarMenuFitLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   remove image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuRemove {
            get {
                return ResourceManager.GetString("AppbarMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuSelect {
            get {
                return ResourceManager.GetString("AppbarMenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   set current lock screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppbarMenuSetLockscreen {
            get {
                return ResourceManager.GetString("AppbarMenuSetLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extra apps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppCategoryExtra {
            get {
                return ResourceManager.GetString("AppCategoryExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   system apps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppCategorySystem {
            get {
                return ResourceManager.GetString("AppCategorySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attentive Phone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcAttentivePhone {
            get {
                return ResourceManager.GetString("AppKeyHtcAttentivePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beats Audio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcBeatsAudio {
            get {
                return ResourceManager.GetString("AppKeyHtcBeatsAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Setup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcConnectionSetup {
            get {
                return ResourceManager.GetString("AppKeyHtcConnectionSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcConverter {
            get {
                return ResourceManager.GetString("AppKeyHtcConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flashlight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcFlashLight {
            get {
                return ResourceManager.GetString("AppKeyHtcFlashLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcHtc {
            get {
                return ResourceManager.GetString("AppKeyHtcHtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make More Space과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcMakeMoreSpace {
            get {
                return ResourceManager.GetString("AppKeyHtcMakeMoreSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Photo Enhancer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyHtcPhotoEnhancer {
            get {
                return ResourceManager.GetString("AppKeyHtcPhotoEnhancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accessories과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaAccessories {
            get {
                return ResourceManager.GetString("AppKeyNokiaAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Point과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaAccessPoint {
            get {
                return ResourceManager.GetString("AppKeyNokiaAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaAccount {
            get {
                return ResourceManager.GetString("AppKeyNokiaAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Social과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaAppSocial {
            get {
                return ResourceManager.GetString("AppKeyNokiaAppSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaAudio {
            get {
                return ResourceManager.GetString("AppKeyNokiaAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creative Studio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaCreativeStudio {
            get {
                return ResourceManager.GetString("AppKeyNokiaCreativeStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display+Touch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaDisplayTouch {
            get {
                return ResourceManager.GetString("AppKeyNokiaDisplayTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra+Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaExtraInfo {
            get {
                return ResourceManager.GetString("AppKeyNokiaExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feedback과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaFeedback {
            get {
                return ResourceManager.GetString("AppKeyNokiaFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Nokia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaMyNokia {
            get {
                return ResourceManager.GetString("AppKeyNokiaMyNokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network+과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNetwork {
            get {
                return ResourceManager.GetString("AppKeyNokiaNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Care과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaCare {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Glam Me과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaGlamMe {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaGlamMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Music과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaMusic {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Pro Cam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaProCam {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaProCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Smart Cam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaSmartCam {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaSmartCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Trailers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaTrailers {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Video Trimmer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaVideoTrimmer {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaVideoTrimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Video Upload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaVideoUpload {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaVideoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokia Xpress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaNokiaXpress {
            get {
                return ResourceManager.GetString("AppKeyNokiaNokiaXpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panorama과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaPanorama {
            get {
                return ResourceManager.GetString("AppKeyNokiaPanorama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PhotoBeamer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaPhotoBeamer {
            get {
                return ResourceManager.GetString("AppKeyNokiaPhotoBeamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play to과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaPlayTo {
            get {
                return ResourceManager.GetString("AppKeyNokiaPlayTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ringtone Maker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaRingtoneMaker {
            get {
                return ResourceManager.GetString("AppKeyNokiaRingtoneMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smart Shoot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaSmartShoot {
            get {
                return ResourceManager.GetString("AppKeyNokiaSmartShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SophieLens For Nokia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaSophieLensForNokia {
            get {
                return ResourceManager.GetString("AppKeyNokiaSophieLensForNokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer my Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeyNokiaTransferMyData {
            get {
                return ResourceManager.GetString("AppKeyNokiaTransferMyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional call settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungAddtionalCallSettings {
            get {
                return ResourceManager.GetString("AppKeySamsungAddtionalCallSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced text messages과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungAdvancedTextMessages {
            get {
                return ResourceManager.GetString("AppKeySamsungAdvancedTextMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APNs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungApns {
            get {
                return ResourceManager.GetString("AppKeySamsungApns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ativ Beam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungAtivBeam {
            get {
                return ResourceManager.GetString("AppKeySamsungAtivBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beauty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungBeauty {
            get {
                return ResourceManager.GetString("AppKeySamsungBeauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   call blocking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungCallBlocking {
            get {
                return ResourceManager.GetString("AppKeySamsungCallBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChatON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungChatOn {
            get {
                return ResourceManager.GetString("AppKeySamsungChatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contacts import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungContactsImport {
            get {
                return ResourceManager.GetString("AppKeySamsungContactsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Live Wallpaper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungLiveWallpaper {
            get {
                return ResourceManager.GetString("AppKeySamsungLiveWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MiniDiary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungMiniDiary {
            get {
                return ResourceManager.GetString("AppKeySamsungMiniDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music Hub과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungMusicHub {
            get {
                return ResourceManager.GetString("AppKeySamsungMusicHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungNow {
            get {
                return ResourceManager.GetString("AppKeySamsungNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Photo Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungPhotoEditor {
            get {
                return ResourceManager.GetString("AppKeySamsungPhotoEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Photogram과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungPhotogram {
            get {
                return ResourceManager.GetString("AppKeySamsungPhotogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS Times과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppKeySamsungRssTimes {
            get {
                return ResourceManager.GetString("AppKeySamsungRssTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chameleon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   and {0} people과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AttenddesAccPerson {
            get {
                return ResourceManager.GetString("AttenddesAccPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   battery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   battery charging과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatteryCharging {
            get {
                return ResourceManager.GetString("BatteryCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   remaining과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatteryRemaining {
            get {
                return ResourceManager.GetString("BatteryRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adult과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchAdult {
            get {
                return ResourceManager.GetString("BingSearchAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   aspect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchAspect {
            get {
                return ResourceManager.GetString("BingSearchAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchColor {
            get {
                return ResourceManager.GetString("BingSearchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   face과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchFace {
            get {
                return ResourceManager.GetString("BingSearchFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchOptions {
            get {
                return ResourceManager.GetString("BingSearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   maximum count of query results과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchQueryCount {
            get {
                return ResourceManager.GetString("BingSearchQueryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchSize {
            get {
                return ResourceManager.GetString("BingSearchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingSearchStyle {
            get {
                return ResourceManager.GetString("BingSearchStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bing today과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingToday {
            get {
                return ResourceManager.GetString("BingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BingWeb {
            get {
                return ResourceManager.GetString("BingWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   black list과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   buy the full version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   calendar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   display appointment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalendarDisplayAppointment {
            get {
                return ResourceManager.GetString("CalendarDisplayAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   first day of week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalendarFirstDayOfWeek {
            get {
                return ResourceManager.GetString("CalendarFirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Washington, D.C.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amber과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorAmber {
            get {
                return ResourceManager.GetString("ColorAmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorBrown {
            get {
                return ResourceManager.GetString("ColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chrome과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorChrome {
            get {
                return ResourceManager.GetString("ColorChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cobalt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorCobalt {
            get {
                return ResourceManager.GetString("ColorCobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crimson과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorCrimson {
            get {
                return ResourceManager.GetString("ColorCrimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorCyan {
            get {
                return ResourceManager.GetString("ColorCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emerald과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorEmerald {
            get {
                return ResourceManager.GetString("ColorEmerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indigo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorIndigo {
            get {
                return ResourceManager.GetString("ColorIndigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Gray과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorLightGray {
            get {
                return ResourceManager.GetString("ColorLightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorLime {
            get {
                return ResourceManager.GetString("ColorLime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magenta과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorMagenta {
            get {
                return ResourceManager.GetString("ColorMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mauve과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorMauve {
            get {
                return ResourceManager.GetString("ColorMauve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Olive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorOlive {
            get {
                return ResourceManager.GetString("ColorOlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orange과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorOrange {
            get {
                return ResourceManager.GetString("ColorOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorPink {
            get {
                return ResourceManager.GetString("ColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sienna과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorSienna {
            get {
                return ResourceManager.GetString("ColorSienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorSteel {
            get {
                return ResourceManager.GetString("ColorSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorTeal {
            get {
                return ResourceManager.GetString("ColorTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   transparent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorTransparent {
            get {
                return ResourceManager.GetString("ColorTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Violet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorViolet {
            get {
                return ResourceManager.GetString("ColorViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yellow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cut과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   custom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}d과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DayShortener {
            get {
                return ResourceManager.GetString("DayShortener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   disable location detection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisableLocationDetection {
            get {
                return ResourceManager.GetString("DisableLocationDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   domain filter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DomainFilter {
            get {
                return ResourceManager.GetString("DomainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   enable highlighting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableHighlighting {
            get {
                return ResourceManager.GetString("EnableHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extra과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   face과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   facebook과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   feedback과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FixSkinColor {
            get {
                return ResourceManager.GetString("FixSkinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   flip horizontal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FlipToHorizontal {
            get {
                return ResourceManager.GetString("FlipToHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   flip vertical과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FlipToVertical {
            get {
                return ResourceManager.GetString("FlipToVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   graphics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hide from menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HideMenu {
            get {
                return ResourceManager.GetString("HideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}hr과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HourShortener {
            get {
                return ResourceManager.GetString("HourShortener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   images과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   search web과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageSearch {
            get {
                return ResourceManager.GetString("ImageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageSettings {
            get {
                return ResourceManager.GetString("ImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusAdd {
            get {
                return ResourceManager.GetString("ImageStatusAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   added과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusAdded {
            get {
                return ResourceManager.GetString("ImageStatusAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adding...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusAdding {
            get {
                return ResourceManager.GetString("ImageStatusAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusDownload {
            get {
                return ResourceManager.GetString("ImageStatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   downloaded과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusDownloaded {
            get {
                return ResourceManager.GetString("ImageStatusDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   downloading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusDownloading {
            get {
                return ResourceManager.GetString("ImageStatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusFailAdd {
            get {
                return ResourceManager.GetString("ImageStatusFailAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusFailDownload {
            get {
                return ResourceManager.GetString("ImageStatusFailDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusFailSave {
            get {
                return ResourceManager.GetString("ImageStatusFailSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   time out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImageStatusTimeOut {
            get {
                return ResourceManager.GetString("ImageStatusTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arabic(Arabia)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageRegion_ar_XA {
            get {
                return ResourceManager.GetString("LanguageRegion_ar_XA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English(Indonesia)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageRegion_en_ID {
            get {
                return ResourceManager.GetString("LanguageRegion_en_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English(Arabia)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageRegion_en_XA {
            get {
                return ResourceManager.GetString("LanguageRegion_en_XA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spanish(Latin America)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageRegion_es_XL {
            get {
                return ResourceManager.GetString("LanguageRegion_es_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slovenian(Slovenia)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageRegion_sl_SL {
            get {
                return ResourceManager.GetString("LanguageRegion_sl_SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   large과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   live tiles과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LiveTiles {
            get {
                return ResourceManager.GetString("LiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main live tiles background color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LivetilesMainBackgroundColor {
            get {
                return ResourceManager.GetString("LivetilesMainBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main live tiles template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LivetilesMainTemplate {
            get {
                return ResourceManager.GetString("LivetilesMainTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub live tiles background color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LivetilesSubBackgroundColor {
            get {
                return ResourceManager.GetString("LivetilesSubBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub live tiles template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LivetilesSubTemplate {
            get {
                return ResourceManager.GetString("LivetilesSubTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lock screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lockscreen {
            get {
                return ResourceManager.GetString("Lockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   background separation of items 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenBackgroundItemSeparation {
            get {
                return ResourceManager.GetString("LockscreenBackgroundItemSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   background color of items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenItemBackgroundColor {
            get {
                return ResourceManager.GetString("LockscreenItemBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   background opacity of items ({0}%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenItemBackgroundOpacity {
            get {
                return ResourceManager.GetString("LockscreenItemBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   template of display items (weather etc.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenItemBackgroundTemplate {
            get {
                return ResourceManager.GetString("LockscreenItemBackgroundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   foreground color of items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenItemForegroundColor {
            get {
                return ResourceManager.GetString("LockscreenItemForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   foreground opacity of items ({0}%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenItemForegroundOpacity {
            get {
                return ResourceManager.GetString("LockscreenItemForegroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weather in the region that are retrieved from a weather menu will be displayed here.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LockscreenNoWeatherData {
            get {
                return ResourceManager.GetString("LockscreenNoWeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Apps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManufacturereApps {
            get {
                return ResourceManager.GetString("ManufacturereApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   medium과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   moderate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Moderate {
            get {
                return ResourceManager.GetString("Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monochrome과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Monochrome {
            get {
                return ResourceManager.GetString("Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to exclude this domain when you search?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgAllowDomainFilter {
            get {
                return ResourceManager.GetString("MsgAllowDomainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking the current position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCheckingLocation {
            get {
                return ResourceManager.GetString("MsgCheckingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCityEx {
            get {
                return ResourceManager.GetString("MsgCityEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app accesses your phone&apos;s location. Is that ok?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgConfirmUseLocation {
            get {
                return ResourceManager.GetString("MsgConfirmUseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter City.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgEnterCity {
            get {
                return ResourceManager.GetString("MsgEnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a keyword to search for.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgEnterSearchKeyword {
            get {
                return ResourceManager.GetString("MsgEnterSearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can search by zip code. (U.S. only)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgEnteryAsEng {
            get {
                return ResourceManager.GetString("MsgEnteryAsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error has occurred in the message received from the weather server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgErrorWeatherServerMsg {
            get {
                return ResourceManager.GetString("MsgErrorWeatherServerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not be added to the list of the lock screen. cause : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailAddLockscreen {
            get {
                return ResourceManager.GetString("MsgFailAddLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock screen image is a maximum of {0}. To add more, please delete the existing lock screen image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailAddMaxCount {
            get {
                return ResourceManager.GetString("MsgFailAddMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location is disabled in phone settings. Enable location service?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailLocationService {
            get {
                return ResourceManager.GetString("MsgFailLocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the image. cause : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailSaveImage {
            get {
                return ResourceManager.GetString("MsgFailSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weather service is temporarily unavailable. Please try again in a few minutes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailWeatherService {
            get {
                return ResourceManager.GetString("MsgFailWeatherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a Word, tap the search button can be downloaded an image from the Web.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoDataBingImage {
            get {
                return ResourceManager.GetString("MsgNoDataBingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a city name and tap the search button you can add the city.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoDataCity {
            get {
                return ResourceManager.GetString("MsgNoDataCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap the Add button below, you can add a picture.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoDataLockscreen {
            get {
                return ResourceManager.GetString("MsgNoDataLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no application that is available in this mobile phone.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoDataMfApps {
            get {
                return ResourceManager.GetString("MsgNoDataMfApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap the Search button below, you can add a City.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoDataWeather {
            get {
                return ResourceManager.GetString("MsgNoDataWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No result found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoResultCity {
            get {
                return ResourceManager.GetString("MsgNoResultCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This area is not provided by the real-time weather.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNotSupportWeatherLocation {
            get {
                return ResourceManager.GetString("MsgNotSupportWeatherLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current weather is in the query.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgQueryLiveWeather {
            get {
                return ResourceManager.GetString("MsgQueryLiveWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Has been added to the list of the lock screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSuccessAddLockscreen {
            get {
                return ResourceManager.GetString("MsgSuccessAddLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image has been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSuccessSaveImage {
            get {
                return ResourceManager.GetString("MsgSuccessSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already been deleted or can not be loaded image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgWrongImage {
            get {
                return ResourceManager.GetString("MsgWrongImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   other과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   photo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   portrait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protective coloration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProtectiveColor {
            get {
                return ResourceManager.GetString("ProtectiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rate &amp; review과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RateReview {
            get {
                return ResourceManager.GetString("RateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rotate left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RotateToLeft {
            get {
                return ResourceManager.GetString("RotateToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rotate right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RotateToRight {
            get {
                return ResourceManager.GetString("RotateToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   searching...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   search language and marketplace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchLanguageMarketplace {
            get {
                return ResourceManager.GetString("SearchLanguageMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select picture과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bing common과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingGroupBingCommon {
            get {
                return ResourceManager.GetString("SettingGroupBingCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bing search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingGroupBingSearch {
            get {
                return ResourceManager.GetString("SettingGroupBingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random background image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkinImage {
            get {
                return ResourceManager.GetString("SkinImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   small과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   square과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   strict과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Strict {
            get {
                return ResourceManager.GetString("Strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tall {
            get {
                return ResourceManager.GetString("Tall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} updated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleOfWeatherCity {
            get {
                return ResourceManager.GetString("TitleOfWeatherCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   transform과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update cycle for live tiles과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTermLivetiles {
            get {
                return ResourceManager.GetString("UpdateTermLivetiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update cycle for lock screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTermLockscreen {
            get {
                return ResourceManager.GetString("UpdateTermLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weather과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   current location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherCurrentLocation {
            get {
                return ResourceManager.GetString("WeatherCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   feels like {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherLiveFeelsLike {
            get {
                return ResourceManager.GetString("WeatherLiveFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   humidity {0}{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherLiveHumidity {
            get {
                return ResourceManager.GetString("WeatherLiveHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wind {0} {1}{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherLiveWind {
            get {
                return ResourceManager.GetString("WeatherLiveWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   search city과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherSearchCity {
            get {
                return ResourceManager.GetString("WeatherSearchCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   display unit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherUnit {
            get {
                return ResourceManager.GetString("WeatherUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Celsius (°C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherUnitCelsius {
            get {
                return ResourceManager.GetString("WeatherUnitCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fahrenheit (°F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WeatherUnitFahrenheit {
            get {
                return ResourceManager.GetString("WeatherUnitFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Wide {
            get {
                return ResourceManager.GetString("Wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
